title: Zhongzheng Li | Humanoid Robotics
page-top-title: Zhongzheng Li
top-section-bg-text: >-
  <span class="hero-name">Teaching robots to adapt in the real world.</span>
home-subtitle: Zhongzheng Li&ensp;|&ensp;李中政
copyright-text: "COPYRIGHT_PLACEHOLDER"
